// Runtime access to the built-in patch library (public/library/, generated by
// scripts/build-patch-library.mts). Fetches are cached; .syx files are parsed
// on the main thread with the same engine loader the worklet uses.

import { loadSysexFile } from '@texed/dx7-format/sysex-loader';
import { voiceFromRawVced } from '@texed/dx7-format/sysex';
import { AMEM_SLOT_SIZE } from '@texed/dx7-format/amem';
import { VoiceLibrary, type VoiceBankId } from '@texed/dx7-format/voice-library';
import { VOICE_SIZE, VOICES_PER_BANK } from '@texed/dx7-format/voice';
import {
  isLibraryManifest,
  type LibBank,
  type LibCollection,
  type LibraryManifest,
  type LibSet,
} from '@texed/dx7-format/library-manifest';

/** A VCED is the voice without the operator on/off byte the editor adds. */
const VCED_SIZE = VOICE_SIZE - 1;

function libraryUrl(file: string): string {
  return `${import.meta.env.BASE_URL}library/${file}`;
}

export interface ManifestResult {
  manifest: LibraryManifest | null;
  /** Why the library is missing, for the UI to report. Null on success. */
  error: string | null;
}

let manifestPromise: Promise<ManifestResult> | null = null;

/**
 * Fetch the manifest once. A missing library is not fatal (the app still loads
 * dropped .syx files), so this resolves with a reason instead of rejecting.
 */
export function fetchLibraryManifest(): Promise<ManifestResult> {
  manifestPromise ??= fetch(libraryUrl('manifest.json'))
    .then(async (r) => {
      if (!r.ok) return { manifest: null, error: `library manifest ${r.status}` };
      const json: unknown = await r.json();
      return isLibraryManifest(json)
        ? { manifest: json, error: null }
        : { manifest: null, error: 'library manifest is malformed' };
    })
    .catch((err: unknown) => ({
      manifest: null,
      error: err instanceof Error ? err.message : 'library manifest unreachable',
    }));
  return manifestPromise;
}

const blobCache = new Map<string, Promise<Uint8Array>>();

function getBlob(file: string): Promise<Uint8Array> {
  let p = blobCache.get(file);
  if (!p) {
    p = fetch(libraryUrl(file)).then(async (r) => {
      if (!r.ok) throw new Error(`fetch failed: ${file} (${r.status})`);
      return new Uint8Array(await r.arrayBuffer());
    });
    p.catch(() => blobCache.delete(file));
    blobCache.set(file, p);
  }
  return p;
}

const parsedSyxCache = new Map<string, Promise<VoiceLibrary>>();

function getParsedSyx(file: string): Promise<VoiceLibrary> {
  let p = parsedSyxCache.get(file);
  if (!p) {
    p = getBlob(file).then((bytes) => loadSysexFile(bytes).library);
    p.catch(() => parsedSyxCache.delete(file));
    parsedSyxCache.set(file, p);
  }
  return p;
}

/** The bank a set's slot points at, or undefined when the manifest is stale. */
export function bankById(collection: LibCollection, id: string): LibBank | undefined {
  return collection.banks.find((b) => b.id === id);
}

export interface LibVoiceData {
  /** 156-byte unpacked voice. */
  voice: Uint8Array;
  /** 35-byte AMEM supplement when the source carries one. */
  supplement?: Uint8Array;
}

/** Bytes for one voice of a manifest bank, ready for synth.setVoice. */
export async function getVoiceBytes(bank: LibBank, index: number): Promise<LibVoiceData> {
  if (bank.format === 'vced155') {
    const blob = await getBlob(bank.file);
    const raw = blob.subarray(index * VCED_SIZE, (index + 1) * VCED_SIZE);
    const voice = voiceFromRawVced(raw);
    if (!voice) throw new Error(`bad VCED slice ${bank.id}#${index}`);
    return { voice };
  }
  const lib = await getParsedSyx(bank.file);
  const slot = lib.resolve({ bank: bank.sourceBank ?? 'internalA', program: index });
  if (!slot) throw new Error(`bank not in file: ${bank.id}`);
  return { voice: slot.vmem.slice(), supplement: slot.amem.slice() };
}

export interface LibBankData {
  /** 32 × 156-byte voices, concatenated (short banks init-padded by the engine). */
  voices: Uint8Array;
  /** 32 × 35-byte supplements when the source carries them. */
  supplements?: Uint8Array;
}

/** 32 voices starting at `start`, packed for synth.loadBankInto. */
export async function getBankVoices(bank: LibBank, start = 0): Promise<LibBankData> {
  const count = Math.max(0, Math.min(VOICES_PER_BANK, bank.voices.length - start));
  const voices = new Uint8Array(count * VOICE_SIZE);
  if (bank.format === 'vced155') {
    const blob = await getBlob(bank.file);
    for (let i = 0; i < count; i++) {
      const raw = blob.subarray((start + i) * VCED_SIZE, (start + i + 1) * VCED_SIZE);
      const voice = voiceFromRawVced(raw);
      if (voice) voices.set(voice, i * VOICE_SIZE);
    }
    return { voices };
  }
  const lib = await getParsedSyx(bank.file);
  const supplements = new Uint8Array(count * AMEM_SLOT_SIZE);
  for (let i = 0; i < count; i++) {
    const slot = lib.resolve({ bank: bank.sourceBank ?? 'internalA', program: start + i });
    if (slot) {
      voices.set(slot.vmem.subarray(0, VOICE_SIZE), i * VOICE_SIZE);
      supplements.set(slot.amem.subarray(0, AMEM_SLOT_SIZE), i * AMEM_SLOT_SIZE);
    }
  }
  return { voices, supplements };
}

export interface LibVoiceHit {
  collectionId: string;
  collectionName: string;
  bank: LibBank;
  index: number;
  name: string;
  /** Lowercase "name bank collection" haystack for substring search. */
  haystack: string;
}

/** Flat search index over every built-in voice. */
export function buildSearchIndex(manifest: LibraryManifest): LibVoiceHit[] {
  const hits: LibVoiceHit[] = [];
  for (const c of manifest.collections) {
    for (const b of c.banks) {
      b.voices.forEach((name, index) => {
        hits.push({
          collectionId: c.id,
          collectionName: c.name,
          bank: b,
          index,
          name,
          haystack: `${name} ${b.name} ${c.name}`.toLowerCase(),
        });
      });
    }
  }
  return hits;
}

/** The synth methods the set loaders need (subset of Synth). */
export interface SetLoaderSynth {
  loadBankInto: (bank: VoiceBankId, voices: Uint8Array, supplements?: Uint8Array) => void;
  loadCart: (data: ArrayBuffer) => void;
  selectPerformance: (index: number) => void;
}

/** The set's banks, resolved and paired with the slot each one fills. */
function slotBanks(
  collection: LibCollection,
  set: LibSet,
): { slot: VoiceBankId; bank: LibBank; start: number }[] {
  const out: { slot: VoiceBankId; bank: LibBank; start: number }[] = [];
  for (const s of set.slots) {
    const bank = bankById(collection, s.bankId);
    if (bank) out.push({ slot: s.slot, bank, start: s.start ?? 0 });
  }
  return out;
}

/**
 * Load a set into the rack: its voice banks into the half-bank slots the
 * grouping worked out, then the file carrying its performances. Worklet
 * messages are processed in order, so this is race-free.
 */
export async function loadSet(
  synth: SetLoaderSynth,
  collection: LibCollection,
  set: LibSet,
): Promise<void> {
  const staged = await Promise.all(
    slotBanks(collection, set).map(async (s) => ({
      slot: s.slot,
      data: await getBankVoices(s.bank, s.start),
    })),
  );
  for (const { slot, data } of staged) {
    synth.loadBankInto(slot, data.voices, data.supplements);
  }
  if (set.perfFile) {
    const perfBytes = await getBlob(set.perfFile);
    synth.loadCart(perfBytes.slice().buffer as ArrayBuffer);
  }
}

/** Load a set and select one of its performances. */
export async function loadPerformanceFromSet(
  synth: SetLoaderSynth,
  collection: LibCollection,
  set: LibSet,
  index: number,
): Promise<void> {
  await loadSet(synth, collection, set);
  synth.selectPerformance(index);
}

/** One part of one performance, as the browser shows it. */
export interface PerfPartVoice {
  part: number;
  enabled: boolean;
  /** "INT 05 BRASS   1", or "… (bank not loaded)" when the set cannot fill it. */
  label: string;
}

const perfVoiceCache = new Map<string, Promise<PerfPartVoice[][]>>();

/**
 * Part voice names for every performance in a set, resolved against exactly
 * the banks `loadSet` would stage. Lazy: the files are the same ones a load
 * fetches, and both share the blob cache.
 */
export function getSetPerfVoices(
  collection: LibCollection,
  set: LibSet,
): Promise<PerfPartVoice[][]> {
  let p = perfVoiceCache.get(set.id);
  if (!p) {
    p = resolveSetPerfVoices(collection, set);
    p.catch(() => perfVoiceCache.delete(set.id));
    perfVoiceCache.set(set.id, p);
  }
  return p;
}

async function resolveSetPerfVoices(
  collection: LibCollection,
  set: LibSet,
): Promise<PerfPartVoice[][]> {
  if (!set.perfFile) return [];
  const perfLib = await getParsedSyx(set.perfFile);

  // Stage the same wiring loadSet applies, so the labels match what you get.
  const staged = new VoiceLibrary();
  for (const { slot, bank, start } of slotBanks(collection, set)) {
    const { voices, supplements } = await getBankVoices(bank, start);
    const count = Math.floor(voices.length / VOICE_SIZE);
    const list: Uint8Array[] = [];
    const amems: Uint8Array[] = [];
    for (let i = 0; i < count; i++) {
      list.push(voices.subarray(i * VOICE_SIZE, (i + 1) * VOICE_SIZE));
      if (supplements)
        amems.push(supplements.subarray(i * AMEM_SLOT_SIZE, (i + 1) * AMEM_SLOT_SIZE));
    }
    staged.loadVoicesInto(slot, list, supplements ? amems : undefined);
  }

  return perfLib.performances.map((perf) =>
    perf.parts.map((part, i) => ({
      part: i,
      enabled: part.enabled !== false,
      label: part.voice ? staged.voiceLabel(part.voice) : 'INIT VOICE',
    })),
  );
}
