// Runtime access to the built-in patch library (public/library/, generated by
// scripts/build-patch-library.mts). Fetches are cached; .syx files are parsed
// on the main thread with the same engine loader the worklet uses.

import { loadSysexFile } from '../engine/sysex-loader';
import { voiceFromRawVced } from '../engine/sysex';
import { AMEM_SLOT_SIZE } from '../engine/amem';
import { VOICE_BANK_ORDER, type VoiceLibrary } from '../engine/voice-library';
import {
  isLibraryManifest,
  type LibBank,
  type LibPerfSet,
  type LibraryManifest,
} from './library-manifest';

const VCED_SIZE = 155;
const VOICE_SIZE = 156;

function libraryUrl(file: string): string {
  return `${import.meta.env.BASE_URL}library/${file}`;
}

let manifestPromise: Promise<LibraryManifest | null> | null = null;

/** Fetch the manifest once; resolves null when unavailable (app still works). */
export function fetchLibraryManifest(): Promise<LibraryManifest | null> {
  manifestPromise ??= fetch(libraryUrl('manifest.json'))
    .then((r) => (r.ok ? r.json() : null))
    .then((json) => (isLibraryManifest(json) ? json : null))
    .catch(() => null);
  return manifestPromise;
}

const blobCache = new Map<string, Promise<Uint8Array>>();

function getBlob(file: string): Promise<Uint8Array> {
  let p = blobCache.get(file);
  if (!p) {
    p = fetch(libraryUrl(file)).then(async (r) => {
      if (!r.ok) throw new Error(`fetch failed: ${file} (${r.status})`);
      return new Uint8Array(await r.arrayBuffer());
    });
    p.catch(() => blobCache.delete(file));
    blobCache.set(file, p);
  }
  return p;
}

const parsedSyxCache = new Map<string, Promise<VoiceLibrary>>();

function getParsedSyx(file: string): Promise<VoiceLibrary> {
  let p = parsedSyxCache.get(file);
  if (!p) {
    p = getBlob(file).then((bytes) => loadSysexFile(bytes).library);
    p.catch(() => parsedSyxCache.delete(file));
    parsedSyxCache.set(file, p);
  }
  return p;
}

export interface LibVoiceData {
  /** 156-byte unpacked voice. */
  voice: Uint8Array;
  /** 35-byte AMEM supplement when the source carries one. */
  supplement?: Uint8Array;
}

/** Bytes for one voice of a manifest bank, ready for synth.setVoice. */
export async function getVoiceBytes(bank: LibBank, index: number): Promise<LibVoiceData> {
  if (bank.format === 'vced155') {
    const blob = await getBlob(bank.file);
    const raw = blob.subarray(index * VCED_SIZE, (index + 1) * VCED_SIZE);
    const voice = voiceFromRawVced(raw);
    if (!voice) throw new Error(`bad VCED slice ${bank.id}#${index}`);
    return { voice };
  }
  const lib = await getParsedSyx(bank.file);
  const slot = lib.resolve({ bank: bank.sourceBank ?? 'internalA', program: index });
  if (!slot) throw new Error(`bank not in file: ${bank.id}`);
  return { voice: slot.vmem.slice(), supplement: slot.amem.slice() };
}

export interface LibBankData {
  /** 32 × 156-byte voices, concatenated (short banks init-padded by the engine). */
  voices: Uint8Array;
  /** 32 × 35-byte supplements when the source carries them. */
  supplements?: Uint8Array;
}

/** 32 voices starting at `start`, packed for synth.loadBankInto. */
export async function getBankVoices(bank: LibBank, start = 0): Promise<LibBankData> {
  const count = Math.max(0, Math.min(32, bank.voices.length - start));
  const voices = new Uint8Array(count * VOICE_SIZE);
  if (bank.format === 'vced155') {
    const blob = await getBlob(bank.file);
    for (let i = 0; i < count; i++) {
      const raw = blob.subarray((start + i) * VCED_SIZE, (start + i + 1) * VCED_SIZE);
      const voice = voiceFromRawVced(raw);
      if (voice) voices.set(voice, i * VOICE_SIZE);
    }
    return { voices };
  }
  const lib = await getParsedSyx(bank.file);
  const supplements = new Uint8Array(count * AMEM_SLOT_SIZE);
  for (let i = 0; i < count; i++) {
    const slot = lib.resolve({ bank: bank.sourceBank ?? 'internalA', program: start + i });
    if (slot) {
      voices.set(slot.vmem.subarray(0, VOICE_SIZE), i * VOICE_SIZE);
      supplements.set(slot.amem.subarray(0, AMEM_SLOT_SIZE), i * AMEM_SLOT_SIZE);
    }
  }
  return { voices, supplements };
}

export interface LibVoiceHit {
  collectionId: string;
  collectionName: string;
  bank: LibBank;
  index: number;
  name: string;
  /** Lowercase "name bank collection" haystack for substring search. */
  haystack: string;
}

/** Flat search index over every built-in voice. */
export function buildSearchIndex(manifest: LibraryManifest): LibVoiceHit[] {
  const hits: LibVoiceHit[] = [];
  for (const c of manifest.collections) {
    for (const b of c.banks) {
      b.voices.forEach((name, index) => {
        hits.push({
          collectionId: c.id,
          collectionName: c.name,
          bank: b,
          index,
          name,
          haystack: `${name} ${b.name} ${c.name}`.toLowerCase(),
        });
      });
    }
  }
  return hits;
}

/** The synth methods loadPerformanceSet needs (subset of DexedSynth). */
export interface PerformanceLoaderSynth {
  loadBankInto: (bank: (typeof VOICE_BANK_ORDER)[number], voices: Uint8Array, supplements?: Uint8Array) => void;
  loadCart: (data: ArrayBuffer) => void;
  selectPerformance: (index: number) => void;
}

/**
 * Load a built-in performance set and select performance `index`: first the
 * voice banks it references (internalA..cartridgeB order), then the file
 * carrying the performances, then the selection. Worklet messages are
 * processed in order, so this is race-free.
 */
export async function loadPerformanceSet(
  synth: PerformanceLoaderSynth,
  set: LibPerfSet,
  index: number,
): Promise<void> {
  for (let i = 0; i < set.requiresBankFiles.length && i < VOICE_BANK_ORDER.length; i++) {
    const lib = await getParsedSyx(set.requiresBankFiles[i]);
    const source = lib.populatedBanks()[0];
    if (!source) continue;
    const voices = new Uint8Array(32 * VOICE_SIZE);
    const supplements = new Uint8Array(32 * AMEM_SLOT_SIZE);
    for (let p = 0; p < 32; p++) {
      const slot = lib.resolve({ bank: source, program: p });
      if (slot) {
        voices.set(slot.vmem.subarray(0, VOICE_SIZE), p * VOICE_SIZE);
        supplements.set(slot.amem.subarray(0, AMEM_SLOT_SIZE), p * AMEM_SLOT_SIZE);
      }
    }
    synth.loadBankInto(VOICE_BANK_ORDER[i], voices, supplements);
  }
  const perfBytes = await getBlob(set.file);
  synth.loadCart(perfBytes.slice().buffer as ArrayBuffer);
  synth.selectPerformance(index);
}
